# Generated by Django 2.2.4 on 2024-05-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0003_massages_massage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
